name: Rack04 Deployment

on:
  push:
    branches: [ master ]
    paths:
      - "server/**"

defaults:
  run:
    working-directory: server

jobs:
  test:
    name: Deploy to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Set up QEMU
        id: configure-docker-qemu
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: setup-docker-buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: build-and-push-image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: smgdesign/x-tunnel:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
